// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovuOy8sVQEF2xQ6Oe5di7-U5C2SD9HFc',
    appId: '1:777126559500:web:2332bb782f4f164a98d329',
    messagingSenderId: '777126559500',
    projectId: 'aplikasiprivateaja-16651',
    authDomain: 'aplikasiprivateaja-16651.firebaseapp.com',
    storageBucket: 'aplikasiprivateaja-16651.firebasestorage.app',
    measurementId: 'G-HJE6V61BZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQj-4Oev6DgPR5MXSp1vblQ-MXOEOGSiM',
    appId: '1:777126559500:android:9e755c3eafb52ef998d329',
    messagingSenderId: '777126559500',
    projectId: 'aplikasiprivateaja-16651',
    storageBucket: 'aplikasiprivateaja-16651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBriPkBIR9M2a5U9VZTyqZLxiGvXS5zGm0',
    appId: '1:777126559500:ios:8f351b31d640fe5698d329',
    messagingSenderId: '777126559500',
    projectId: 'aplikasiprivateaja-16651',
    storageBucket: 'aplikasiprivateaja-16651.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBriPkBIR9M2a5U9VZTyqZLxiGvXS5zGm0',
    appId: '1:777126559500:ios:8f351b31d640fe5698d329',
    messagingSenderId: '777126559500',
    projectId: 'aplikasiprivateaja-16651',
    storageBucket: 'aplikasiprivateaja-16651.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCovuOy8sVQEF2xQ6Oe5di7-U5C2SD9HFc',
    appId: '1:777126559500:web:f02eb48f490f432598d329',
    messagingSenderId: '777126559500',
    projectId: 'aplikasiprivateaja-16651',
    authDomain: 'aplikasiprivateaja-16651.firebaseapp.com',
    storageBucket: 'aplikasiprivateaja-16651.firebasestorage.app',
    measurementId: 'G-1KESDX01C0',
  );
}
